spring.application.name=Library_Management_System_Backend

# Database Connection URL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/libraryDb?useSSL=false&allowPublicKeyRetrieval=true}

# MySQL credentials
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Hibernate Lifecycle automation strategy
spring.jpa.hibernate.ddl-auto=update

# Useful for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true