spring.application.name=Library_Management_System_Backend

# Database Connection URL
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:10.186.23.78}:${MYSQL_PORT:3306}/${MYSQL_DB:libraryDb}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MySQL credentials
spring.datasource.username=root
spring.datasource.password=1234

# Hibernate Lifecycle automation strategy
spring.jpa.hibernate.ddl-auto=update

# Useful for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true