spring.application.name=Library_Management_System_Backend

# Database Connection URL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/libraryDb?useSSL=false&allowPublicKeyRetrieval=true}

# MySQL credentials
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Hibernate Lifecycle automation strategy
spring.jpa.hibernate.ddl-auto=update

# Useful for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Cache Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Apache Kafka Cluster Environment Routing Configurations
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Consumer/Producer default JSON data formatting blueprints
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.group-id=library-audit-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Mute Kafka's internal verbose configuration dumps
logging.level.org.apache.kafka=WARN
logging.level.org.apache.kafka.clients.producer.ProducerConfig=WARN
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=WARN